### ISSUE TITLE
How to use this with Vue.js?

### ISSUE THREAD

**Issue by sajjadalis** [jorgerosal/amazon-paapi#1]
Hello,

I have been trying to work around with amazon new api but i can't get it working with vue.js.

For example, i just created a new Vue project. Added `const amazonPaapi = require('amazon-paapi');` in Home.vue file and error.

```
Failed to compile.
./node_modules/amazon-paapi/SDK/src/index.js
Module not found: Error: Can't resolve 'ApiClient' in 'D:\Apps\Amazon\vue-amazon-paapi\node_modules\amazon-paapi\SDK\src'
```
http://prntscr.com/s56yiz
https://github.com/sajjadalis/vue-amazon-paapi/blob/master/src/views/Home.vue

I tried official sdk from amazon and amazon paapi wrapper available on github but had similar issues. And It works fine if i add everything inside amazon.js file and try "node amazon.js". I get the response. 

I'm not sure if i'm doing something wrong. Is there anyway to properly use this with Vue.js?

Thanks

**Comment by jorgerosal** [comment]
Hello @sajjadalis,
 
I don't know much about Vue so I can't provide you specific solution. As far as I can tell, it needs a compiler for you to be able to run the SDK directly to the client. The amazon SDK uses ES6+ version of javascript on its code. If you directly use the code to the client-side, it won't be able to recognize the syntax. Therefore you receive compile error. Try [webpack](https://webpack.js.org/), [browserify](https://github.com/browserify/browserify) or something similar.

I hope you find a solution. :)

**Comment by sajjadalis** [comment]
Thanks @jorgerosal  for the reply.

Its already using Webpack. with Vue CLI. I can import other Node modules very fine. Only this one have issues.

Here is the repository if anyone can help.. https://github.com/sajjadalis/vue-amazon-paapi

Thanks

**Comment by uriyahr** [comment]
Hi @sajjadalis  

A few solutions to your issue might be 
1. Try to replace const amazonPaapi = require('amazon-paapi'); with 
    import amazonPaapi from 'amazon-paapi' 

2. Import the npm module from inside of your main.js (vue-amazon-paapi/src/main.js)
    import amazonPaapi from 'amazon-paapi'
    Vue.use(amazonPaapi) 

3. Create a server file 'server.js' outside of vue-amazon-paapi/src (where all of vue stuff is). In the server you can set up your backend to make calls like importing amazonPaapi and configuring.

Heres an article I think could help with 3 : 
https://medium.com/@jaouad_45834/basic-chat-web-app-using-express-js-vue-js-socket-io-429588e841f0

Hope this helps! Happy coding 👍

**Comment by dalezak** [comment]
@jorgerosal did your suggestion to use import amazonPaapi from 'amazon-paapi' work for you? 

I’m receiving errors, looks like others are also having issues https://github.com/jorgerosal/amazon-paapi/issues/21 with Vue.
