### ISSUE TITLE
Response Headers Support

### ISSUE THREAD

**Issue by Jaysparkexel** [jorgerosal/amazon-paapi#10]
Hi, I'm using this package to get Product details using ASIN. Is there any way to access the response header along with the data?

**Comment by jorgerosal** [comment]
Hello @Jaysparkexel, the current setup would be to mimic the same response data we get from the amazon paapi scratchpad. But will think about it.
https://webservices.amazon.com/paapi5/scratchpad/index.html

**Comment by Jaysparkexel** [comment]
Thanks, I already made a few changes in Amazon SDK to get the header's info.
