### ISSUE TITLE
GetItems - Offers.Listings.MerchantInfo is incorrect with feedback*

### ISSUE THREAD

**Issue by success-0627** [jorgerosal/amazon-paapi#11]
**Correct Response**
```json
"MerchantInfo": {
  "DefaultShippingCountry": "GB",
  "FeedbackCount": 2952,
  "FeedbackRating": 4.87,
  "Id": "A12ZT4ZURPEEJ7",
  "Name": "Peter Pann"
},
```

**Current Response**
```json
"MerchantInfo": {
    "DefaultShippingCountry": "GB",
    "Id": "A12ZT4ZURPEEJ7",
    "Name": "Peter Pann"
},
```

**Comment by success-0627** [comment]
A question.
Why do you need to map response to your models then response?
Could it possible to forward was response to user directly without mapping?

**Comment by jorgerosal** [comment]
Hello @zl910627, thank you for the feedback. It's actually from the previous SDK field setup. I'll push your PR but will add and update SDK at a later time since a lot has changed and more fields have been added.
