### ISSUE TITLE
(doc issue) "Resource" in requestParameters should be "Resources", right?

### ISSUE THREAD

**Issue by danielo17** [jorgerosal/amazon-paapi#15]
Hello Jorge,

Not really an issue to be corrected, but I´ve turned around for some hours trying to figure out why the image URL and other resources were not returned.

I started from your doc and the samples you provide. There you use a "Resource" parameter in "requestParameters" when calling.

Testing randomly I changed that to "Resources" and then it worked.

Maybe you want to update the examples and doc, so that others don´t get confused.

Many thanks in any case for this library. Very easy to use and intuitive!

Daniel

**Comment by jorgerosal** [comment]
Oh, You mean this? https://github.com/jorgerosal/amazon-paapi/blob/master/sample/searchItems.js#L17
I will update and correct. Thank you for pointing that out. :)

Happy to know you're using this library. Have a great day.

**Comment by danielo17** [comment]
Yes!, 

but there is another place. Here: https://github.com/jorgerosal/amazon-paapi/blob/master/README.md

Regards

**Comment by chikurin66** [comment]
There is another typo.
Please fix this too.

`https://www.npmjs.com/package/amazon-paapi`

![スクリーンショット 2021-07-07 22 11 55](https://user-images.githubusercontent.com/20056490/124765724-36493d00-df71-11eb-8c6a-d7b10d6eae94.png)

**Comment by jorgerosal** [comment]
This is fixed. Thank you for pointing that out.
