### ISSUE TITLE
querystring module doesn't exist

### ISSUE THREAD

**Issue by jeffreytung7** [jorgerosal/amazon-paapi#20]
When deploying to production, it failed because amazon-paapi/SDK/src/ApiClient.js has the line:

module.exports = factory(require('superagent'), require('querystring'));

However, inside package.json there is no querystring module added in "dependencies".

I did 'npm install querystring' on my main project's package.json and it fixed it, but ideally the querystring module should be added as a dependency inside of the amazon-paapi module.

**Comment by jorgerosal** [comment]
Hey! Thanks for bringing that up. I just included the querystring module in the main package.json. Cheers!
