### ISSUE TITLE
TotalCount not working on SearchItems Method

### ISSUE THREAD

**Issue by webdes03** [jorgerosal/amazon-paapi#4]
Maybe it's something I'm doing, but I can't get TotalCount to have any effect on the response of the call. I always get 10 results back regardless of if I leave TotalCount out, set it to 2, or set it to 20. It works if I do it through the Amazon Scratchpad.

**Comment by jorgerosal** [comment]
Hello @webdes03 -- sorry, I can't seem to find TotalCount parameter in the documentation. do you mean itemCount?

**Comment by webdes03** [comment]
Oh yes, sorry, `ItemCount`.

**Comment by jorgerosal** [comment]
Sorry I was away for a while. Did you accidentally use TotalCount as parameter in your code? Or do you still have issue with the response using ItemCount?

Here is a sample code for reference:
https://github.com/jorgerosal/amazon-paapi/blob/master/sample/searchItems.js
