### ISSUE TITLE
Change on module.exports broke my code in production

### ISSUE THREAD

**Issue by jjragomes** [jorgerosal/amazon-paapi#6]
We've been using version 1.0.1 for a long time and this version is locked in our package.json. After a deploy this week we realized that the code stopped working.

After a deep review, we found that you have changed app.js:
// Allow use of default import syntax in TypeScript
module.exports.default = amazonPaapi;

You must tag correctly each released version of amazon-paapi, otherwise it can break code in production like ours.

I saw that in this repo there are no tags, would be nice to have that.

**Comment by jorgerosal** [comment]
Hello @jjragomes , thanks for the feedback. I'll look into it.

**Comment by jorgerosal** [comment]
This has been fixed and v1.0.3 has been published @jjragomes . Thanks again.
